# Generated by Django 4.2.6 on 2023-10-08 14:28

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnimalResident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=10000, null=True)),
                (
                    "slug",
                    models.SlugField(blank=True, editable=False, max_length=10000),
                ),
                ("age", models.CharField(blank=True, max_length=10000, null=True)),
                ("species", models.CharField(blank=True, max_length=10000, null=True)),
                ("story", models.TextField(blank=True, null=True)),
                (
                    "event_suitability",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("All ages", "All ages"),
                            ("7+ ages", "7+ ages"),
                            ("Not suitable", "Not suitable"),
                        ],
                        default="All ages",
                        max_length=10000,
                        null=True,
                    ),
                ),
                (
                    "animal_picture",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="animal picture"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DragonShelterProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "facebook_url",
                    models.URLField(blank=True, max_length=10000, null=True),
                ),
                (
                    "instagram_username",
                    models.CharField(blank=True, max_length=10000, null=True),
                ),
                (
                    "twitter_username",
                    models.CharField(blank=True, max_length=10000, null=True),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("email", models.CharField(blank=True, max_length=10000, null=True)),
                (
                    "whatsapp_number",
                    models.CharField(blank=True, max_length=10000, null=True),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=10000, null=True),
                ),
                ("about", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="image"
                    ),
                ),
            ],
        ),
    ]
