# Generated by Django 4.2.6 on 2023-10-09 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dragonshelterprofile",
            old_name="whatsapp_number",
            new_name="facebook_username",
        ),
        migrations.RenameField(
            model_name="dragonshelterprofile",
            old_name="address",
            new_name="location",
        ),
        migrations.RemoveField(
            model_name="dragonshelterprofile",
            name="facebook_url",
        ),
        migrations.RemoveField(
            model_name="dragonshelterprofile",
            name="image",
        ),
    ]
