# Generated by Django 4.2.6 on 2023-10-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0002_rename_whatsapp_number_dragonshelterprofile_facebook_username_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dragonshelterprofile",
            name="facebook_username",
        ),
        migrations.AddField(
            model_name="dragonshelterprofile",
            name="facebook_url",
            field=models.URLField(blank=True, max_length=10000, null=True),
        ),
    ]
