# Generated by Django 4.2.6 on 2023-10-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_dragonshelterprofile_facebook_username_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dragonshelterprofile",
            old_name="description",
            new_name="short_description",
        ),
        migrations.AddField(
            model_name="dragonshelterprofile",
            name="whatsapp_number",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
