# Generated by Django 4.2.6 on 2023-10-11 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_dragonshelterprofile_booking_enquiries_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookAnEncounterRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10000)),
                ("email", models.CharField(max_length=10000)),
                ("phone_number", models.CharField(max_length=10000)),
                ("event_description", models.TextField()),
                ("preferred_date_of_event", models.CharField(max_length=10000)),
            ],
        ),
    ]
