# Generated by Django 4.2.6 on 2024-01-15 17:25

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_dragonshelterevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaddyPony",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=10000, null=True)),
                ("age", models.CharField(blank=True, max_length=10000, null=True)),
                ("species", models.CharField(blank=True, max_length=10000, null=True)),
                ("story", models.TextField(blank=True, null=True)),
                (
                    "event_suitability",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("All ages", "All ages"),
                            ("7+ ages", "7+ ages"),
                            ("Not suitable", "Not suitable"),
                        ],
                        default="All ages",
                        max_length=10000,
                        null=True,
                    ),
                ),
                (
                    "pony_profile_picture",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="pony profile picture"
                    ),
                ),
                (
                    "photo_1",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="photo 1"
                    ),
                ),
                (
                    "photo_2",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="photo 2"
                    ),
                ),
                (
                    "photo_3",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="photo 3"
                    ),
                ),
                (
                    "photo_4",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="photo 4"
                    ),
                ),
            ],
        ),
    ]
