# Generated by Django 4.2.6 on 2024-01-15 17:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_paddypony"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paddypony",
            name="photo_1",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="photo 1"
            ),
        ),
        migrations.AlterField(
            model_name="paddypony",
            name="photo_2",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="photo 2"
            ),
        ),
        migrations.AlterField(
            model_name="paddypony",
            name="photo_3",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="photo 3"
            ),
        ),
        migrations.AlterField(
            model_name="paddypony",
            name="photo_4",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="photo 4"
            ),
        ),
    ]
